### ISSUE TITLE
cant move offsets or character in character editor

### ISSUE THREAD

**Issue by charlesisfeline** [SlightlySimple/FNF-Restructure-Engine#1]
uhhh i cant move the character in character editor (and/or stage editor) help

**Comment by SlightlySimple** [comment]
Make sure the "Lock" checkbox is unchecked. It's in the "Properties" tab in the Character Editor, and the "Settings" tab in the Stage Editor  
It's on by default to prevent things from being moved by accident

**Comment by charlesisfeline** [comment]
yea obviously because i was just trying out this engine for the first time (i was used to psych and codename btw) but thanks for the advice!
