### ISSUE TITLE
ChartEditorState error

### ISSUE THREAD

**Issue by I-am-someone-sh** [SlightlySimple/FNF-Restructure-Engine#2]
Error: ./src/editors/ChartEditorState.cpp:6379:42: warning: trigraph converted to '\' character [-Wtrigraphs]
HXDLIN(3665)                            _hx_tmp->set_text((HX_("???/",30,76,d4,29) + fn.substring(_hx_tmp1,fn.length)));
                                                                 ^
./src/editors/ChartEditorState.cpp:6379:40: warning: missing terminating '"' character [-Winvalid-pp-token]
HXDLIN(3665)                            _hx_tmp->set_text((HX_("???/",30,76,d4,29) + fn.substring(_hx_tmp1,fn.length)));
                                                               ^
./src/editors/ChartEditorState.cpp:6379:36: error: unterminated function-like macro invocation
HXDLIN(3665)                            _hx_tmp->set_text((HX_("???/",30,76,d4,29) + fn.substring(_hx_tmp1,fn.length)));
                                                           ^
/usr/local/lib/haxe/lib/hxcpp/4,2,1/include/hxcpp.h:175:9: note: macro 'HX_' defined here
#define HX_(s,h0,h1,h2,h3) ::String( const_cast<char *>(( HX_HEX_QUOTE(h0) HX_HEX_QUOTE(h1) HX_HEX_QUOTE(h2) HX_HEX_QUOTE(h3) "\x00\x00\x10\x80" s )) + 8 , sizeof(s)/sizeof(char)-1)
        ^
./src/editors/ChartEditorState.cpp:8425:27: error: expected expression
} // end namespace editors
                          ^
./src/editors/ChartEditorState.cpp:8425:27: error: expected '}'
./src/editors/ChartEditorState.cpp:6376:21: note: to match this '{'
                                else {
                                     ^
./src/editors/ChartEditorState.cpp:8425:27: error: expected '}'
} // end namespace editors
                          ^
./src/editors/ChartEditorState.cpp:6371:20: note: to match this '{'
                        else {
                             ^
./src/editors/ChartEditorState.cpp:8425:27: error: expected '}'
} // end namespace editors
                          ^
./src/editors/ChartEditorState.cpp:6364:45: note: to match this '{'
void ChartEditorState_obj::refreshFilename(){
                                            ^
./src/editors/ChartEditorState.cpp:8425:27: error: expected '}'
} // end namespace editors
                          ^
./src/editors/ChartEditorState.cpp:545:18: note: to match this '{'
namespace editors{
                 ^
2 warnings and 6 errors generated.

**Comment by SlightlySimple** [comment]
Is this an error that you got while the game was running, or an error from trying to compile it?

**Comment by I-am-someone-sh** [comment]
> Is this an error that you got while the game was running, or an error from trying to compile it?

compiling

**Comment by SlightlySimple** [comment]
Restructure Engine uses a lot of outdated versions of Haxe libraries and isn't very optimized for others to compile the source code. This is also a rather weird error that I can only guess stemmed from either a corrupted file, a weird folder structure, or the compiling getting interrupted. It would be better to download a release build and create a mod with it instead of recompiling

**Comment by I-am-someone-sh** [comment]
> Restructure Engine uses a lot of outdated versions of Haxe libraries and isn't very optimized for others to compile the source code. This is also a rather weird error that I can only guess stemmed from either a corrupted file, a weird folder structure, or the compiling getting interrupted. It would be better to download a release build and create a mod with it instead of recompiling

ok
