### ISSUE TITLE
custom noteskins (how do i do them)

### ISSUE THREAD

**Issue by noskincz** [SlightlySimple/FNF-Restructure-Engine#4]
I am using the engine for my first time to try porting a mod that i like (for fun and wont be uploaded anywhere - for me to learn how this engine works) and i have a problem that the noteskin that is on the mod is not one of the default ones (why did i type this its so obvious) and i need some help about adding custom noteskins (and maybe even notesplashes)
the noteskin in question:
![bsodarrows](https://github.com/SlightlySimple/FNF-Restructure-Engine/assets/84130850/35669049-f569-45e9-9988-47c1bc6c645a)

**Comment by SlightlySimple** [comment]
The GitHub page has been updated with an example mod for adding a custom noteskin, and noteskin type. I'll likely make a proper tutorial for this later
[example_mods](https://github.com/SlightlySimple/FNF-Restructure-Engine/tree/main/example_mods)

**Comment by noskincz** [comment]
update: i kinda winged it and made it :D
