### ISSUE TITLE
Feature Request: Sustains should not miss when it is released within the hitLimit window

### ISSUE THREAD

**Issue by anima-ex-inani** [SlightlySimple/FNF-Restructure-Engine#6]
Currently, sustains will miss when the note is released and not pressed after the specified time in `SustainNote.hitLimit` passes. While this works on paper, a problem arises when the note is released at most one `hitLimit` before it passes the strum line.

Since the sustain was not held until its end passes the strum line, the code that checks if the sustain misses (`PlayState.hx:L984`) will always trigger first before the code that destroys the sustain, preventing it from missing (`PlayState.hx:L987`). This will be the case even if the sustain was released one frame too early. If the sustain was released at most one `hitLimit` before the `sustainLength`, this results in the sustain missing even though it is fully past the strum line.

While visually intuitive because you can see the sustain end go past without being hit, this is rather bad for UX. This forces the player to hold the sustain for longer than it needs to be as releasing the sustain close to its actual end risks releasing too early. This could even be worse for roll notes as a note that is within one `hitLimit` of the roll end could be prematurely hit by the final press for the roll note (though this could be a case of bad charting if it happened).

**Comment by SlightlySimple** [comment]
Thank you for the request. Sustains will be changed in the next update to implement it

**Comment by anima-ex-inani** [comment]
Works great. There's a minor bug for it but I think it's a separate issue since this is already resolved.
