### ISSUE TITLE
Visual Bug: Receptor texture gets stuck at its "confirm" textures when releasing a sustain early.

### ISSUE THREAD

**Issue by anima-ex-inani** [SlightlySimple/FNF-Restructure-Engine#7]
The implementation for #6 seems to have brought an issue with how the textures for the receptors are being chosen. From what it looks like, when a receptor is released, it swaps to its regular textures. When pressed without hitting a note, it uses the "pressed" textures. When pressed and a note gets hit, it uses the "confirm" textures.

While a sustain note is being hit, the receptors will always use the "confirm" textures. If `SustainNote.passedHitLimit` is `true`, sustain notes count as being hit even if they actually aren't because of them being released. As such, receptors will use the "confirm" textures. A consequence of this is that since the receptor doesn't get released after the sustain note passes completely (because the receptor isn't being held), the textures don't switch to the regular ones. Only when the receptor is pressed again will it switch to the regular textures.

Steps to reproduce:

1. Play a chart that has at least one sustain.
2. Hit the sustain and release it within the hit limit window so it counts as a hit.

Expected Behavior: The receptor reverts back to its regular texture once the note passes and the receptor isn't pressed.

Actual Behavior: The receptor still looks as if it is still being held, even when that is not the case.

Video of bug in action: <https://streamable.com/h7fefm>

**Comment by anima-ex-inani** [comment]
It doesn't really affect gameplay in any way. Just thought I'd mention it.

**Comment by SlightlySimple** [comment]
Thanks for catching this. I likely didn't catch it myself because I have my strumline animations set to "Non-Held" which causes the strums to reset as expected. I'll fix this ASAP
