### ISSUE TITLE
help

### ISSUE THREAD

**Issue by wolfoudre** [SlightlySimple/FNF-Restructure-Engine#9]
![lp](https://github.com/user-attachments/assets/3680c9c9-9a32-4680-a7e1-9ef7de2ffb24)
![lk](https://github.com/user-attachments/assets/9f469219-597e-4dcb-9f69-fa5f50208801)

**Comment by SlightlySimple** [comment]
All custom assets have to be placed *in* a mod, not just in the `mods` folder itself. You can create a mod by clicking on "Create New Mod" in the Editors menu and filling out the popup window that appears

**Comment by wolfoudre** [comment]
thank you very much
